### ISSUE TITLE
RMMS Modbus master simulator  issue

### ISSUE THREAD

**Issue by SuriyaStar123** [budulinek/arduino-modbus-rtu-tcp-gateway#12]
How to get off this error and write numbers in 0 and check with modscan

![image](https://user-images.githubusercontent.com/83509316/146705607-6d27cc9b-b97b-432e-88a2-149bf0053061.png)

**Comment by budulinek** [comment]
I do not know. 

If you have a "RMMS Modbus master simulator issue", you should probably turn to the author of RMMS Modbus master simulator.

**Comment by budulinek** [comment]
Cannot reproduce, RMMS works for me. Double check your configuration and your modbus request.
