### ISSUE TITLE
 adapt project for stm32

### ISSUE THREAD

**Issue by jmcastillejo** [budulinek/arduino-modbus-rtu-tcp-gateway#2]
I would like to know if it is possible to adapt this project for the stm32f103 "bluepill" or similar

**Comment by budulinek** [comment]
I do not have bluepill at the moment, so I can not test it. 

It should be possible, but you will need to do some changes to the code. See https://github.com/budulinek/arduino-modbus-rtu-tcp-gateway#portability

Also, check the bluepill pinout for serial connections (for RS485) and SPI connections (for ethernet shield).
