### ISSUE TITLE
TCP to RTU gateway

### ISSUE THREAD

**Issue by vitucciog** [budulinek/arduino-modbus-rtu-tcp-gateway#34]
Hi,
I have exactly the opposite need, that is to connect a Modbus TCP slave to a Modbus RTU master. Any possibility to implement it? Or are you aware of project with Arduino or ESP8266 or ESP32 that already do it?

Thanks

**Comment by budulinek** [comment]
No, it is not possible. This project runs on Arduino and there is no place left in the memory to implement this functionality.
 I am not aware of any ESP project but I know there are commercially available bi-directional Modbus converters. For example this one:
https://en.papouch.com/tcp2rtu-modbus-tcp-to-rtu-ascii-converter-p4620/
